# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: CamachoLab Photonics Bootcamp
author: CamachoLab and Google
copyright: "2023"
logo: images/logo.svg

exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    # - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution
    - tasklist
  myst_url_schemes: [mailto, http, https] # URI schemes that will be recognised as external URLs in Markdown links
  myst_dmath_double_inline: true  # Allow display math ($$) within an inline context

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: "images/favicon-laser.svg"  # A path to a favicon image
  use_edit_page_button: true  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button: true  # Whether to add a link to your repository button
  use_issues_button: true  # Whether to add an "open an issue" button
  use_multitoc_numbering: true   # Continuous numbering across parts/chapters
  extra_navbar: Powered by <a href="https://jupyterbook.org">Jupyter Book</a>  # Will be displayed underneath the left navbar.
  extra_footer: ""  # Will be displayed underneath the footer.
  google_analytics_id: ""  # A GA id that can be used to track book views.
  home_page_in_navbar: false  # Whether to include your home page in the left Navigation Bar
  baseurl: "https://byucamacholab.github.io/Photonics-Bootcamp/"  # The base URL where your book will be hosted. Used for creating image previews and social links.
  comments:
    hypothesis: false
    utterances: false
  announcement: "" # A banner announcement at the top of the site.

# Define the name of the latex output file for PDF builds
latex:
  latex_engine: pdflatex  # one of 'pdflatex', 'xelatex' (recommended for unicode), 'luatex', 'platex', 'uplatex'
  use_jupyterbook_latex: true # use sphinx-jupyterbook-latex for pdf builds as default
  latex_documents:
    targetname: book.tex

launch_buttons:
  notebook_interface: classic  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: https://mybinder.org  # The URL of the BinderHub (e.g., https://mybinder.org)
  jupyterhub_url: ""  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  thebe: false  # Add a thebe button to pages (requires the repository to run on Binder)
  colab_url: "" # The URL of Google Colab (https://colab.research.google.com)

# Information about where the book exists on the web
repository:
  url: https://github.com/BYUCamachoLab/Photonics-Bootcamp  # Online location of your book
  path_to_book: book  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

sphinx:
  config:
    language: en
    html_theme_options:
      logo_only: true
